global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'spring-backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8088']

  - job_name: 'tower-simulator'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']

