global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Backend metrics (Spring Boot Actuator)
  - job_name: 'backend'
    static_configs:
      - targets: ['host.docker.internal:8088']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s

  # Simulator metrics (Spring Boot Actuator)
  - job_name: 'simulator'
    static_configs:
      - targets: ['host.docker.internal:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
